const ranges = [[ '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '' ],
  [ new Date("Tue Mar 25 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    new Date("Wed Mar 26 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    new Date("Thu Mar 27 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '' ],
  [ 'HORA',
    'NOMBRE',
    'DOCUMENTO',
    'EPS',
    'SERVICIO',
    'N° SESIÓN',
    'MODALIDAD',
    'FECHA DE AGENDAMIENTO',
    'RESPONSABLE',
    'OBSERVACIONES',
    'TOTAL SESIONES',
    '',
    '',
    'HORA',
    'NOMBRE',
    'DOCUMENTO',
    'EPS',
    'SERVICIO',
    'N° SESIÓN',
    'MODALIDAD',
    'FECHA DE AGENDAMIENTO',
    'RESPONSABLE',
    'OBSERVACIONES',
    'TOTAL SESIONES',
    '',
    '',
    'HORA',
    'NOMBRE',
    'DOCUMENTO',
    'EPS',
    'SERVICIO',
    'N° SESIÓN',
    'MODALIDAD',
    'FECHA DE AGENDAMIENTO',
    'RESPONSABLE',
    'OBSERVACIONES',
    'TOTAL SESIONES' ],
  [ new Date("Sat Dec 30 1899 08:00:00 GMT-0500 (Eastern Standard Time)"),
    'CASTAÑEDA BERMUDEZ MARIANGEL',
    '1025660443_ 14 añosd ',
    'Nueva Eps',
    'RHb Neuro',
    new Date("Wed Oct 01 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    'PRESENCIAL',
    new Date("Sat Mar 01 2025 00:00:00 GMT-0500 (Eastern Standard Time)"),
    'Leslye',
    '313 6555241 - CONFIRMADA ',
    '1',
    '',
    '',
    new Date("Sat Dec 30 1899 08:00:00 GMT-0500 (Eastern Standard Time)"),
    'AGUDELO HERNANDEZ LUCAS',
    '1023545706',
    'Nueva Eps',
    'Administración',
    new Date("Thu May 01 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    'PRESENCIAL',
    new Date("Fri Mar 07 2025 00:00:00 GMT-0500 (Eastern Standard Time)"),
    'Luisa',
    '3106045678 No contesta de envia mensaje de WPP ',
    '0',
    '',
    '',
    new Date("Sat Dec 30 1899 08:00:00 GMT-0500 (Eastern Standard Time)"),
    'URREGO LOPEZ HERNANDO DE JESUS',
    '3362725',
    'Nueva Eps',
    'Administración',
    new Date("Thu May 01 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    'PRESENCIAL',
    new Date("Wed Mar 26 2025 00:00:00 GMT-0400 (Eastern Daylight Time)"),
    'Leslye',
    '3194160161',
    '1' ],
  [ 'TOTAL ATENCIONES',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '11',
    '',
    '',
    'TOTAL ATENCIONES',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '4',
    '',
    '',
    'TOTAL ATENCIONES',
    '',
    '',
    '',
    '',
    '',
    '',
    'TOTAL SESIONES',
    'TOTAL SESIONES',
    '',
    '7' ]
]


export default ranges;